---
title: "DataCamp for the Classroom"
---

This class is supported by [DataCamp](https://www.datacamp.com/home), the most intuitive learning platform for data science. Learn R, Python and SQL the way you learn best through a combination of short expert videos and hands-on-the-keyboard exercises. Take over 100+ courses by expert instructors on topics such as importing data, data visualization or machine learning and learn faster through immediate and personalised feedback on every exercise.

DataCamp for the Classroom offer of high-quality, self-paced content and straightforward, easy-to-use interface for both students and instructors. In particular, enrolling to our `ml4e` DataCamp for the Classroom account will enable you 100% free access to all of DataCamp's content, including their premium content. 

During class, you will be assigned with specific courses and chapters that will help you to catch-up with your R skills whenever you choose to. We encourage you to go over DataCamp's collection of courses and pick-up on the fly any skills that you think might help you going forward!

The link to our DataCamp for the Classroom dashboard:

https://www.datacamp.com/enterprise/machine-learning-for-economists

Make sure to open a DataCamp account. Once you have an account, shoot me (Itamar) an email and I will add you as a member.
