---
title: "Git and GitHub"
---

Git is the *de facto* go-to solution for version control. Think of "track changes" on setroids for code files. GitHub is the leading cloud hosting service of Git repositories. It is kind of a Dropbox on steroids (sorry for repeating a metaphore) for programmers, that enabels efficient code sharing and collaobration.


### Git installation

Go [**here**](http://git-scm.com/downloads) to download a graphical Git installer appropriate for your machine’s operating system (Mac / Windows).

Run the installer and follow its instructions to install the software. Usually the default options are all we need for configuring Git.


### Open a GitHub account
  
Go [**here**](http://github.com) to register an account if you have not got one. It is highly recemmended to choose a straightforward username (e.g., *itamarcaspi* instead of *icaspi99*) so that your are easily found.

### GitHub Desktop installation

GitHub Desktop provides a straightforward GUI interface to git and GitHub. It enables you to easily sync between your local and remote folders and apply basic git commands with a click of a button. 

Go [**here**](https://desktop.github.com/) to download GitHub Desktop, and follow the installation guide. 

### Cloning the `ml4e` repository

Once git, GitHub and GitHub desktop are all set, open GitHub Desktop and go [**here**]() to open our `ml4e` course repository. Once in the repository, klick on the green **Clone or download** button (top right, above the folders and files pane). If done correctly, GitHub Desktop should prompt you with a request for a local destination for the `ml4e` repository. Choose where you want to install your local copy of the `ml4e` repo, click OK, and we're done. 

### Keeping your local `ml4e` repo synced

GitHub Desktop can help you keep your copy of the `ml4e` repo up to date by following these steps:

1. Open GitHub Desktop.
2. Set the Current repository to `ml4e`.
3. Click on the "Fetch origin" button.
4. If it says Pull with a number next to it (e.g., "Pull" +1), click on it and you're done.

### Resources

+ The second chapter of DataCamp's [Working with the RStudio IDE (Part 2)](https://www.datacamp.com/courses/working-with-the-rstudio-ide-part-2) course.

+ DataCamp's [Introduction to Git for Data Science](https://www.datacamp.com/courses/introduction-to-git-for-data-science) course.