---
title: "Resources"
---

__NOTE:__ There are no required textbooks. All materials notes will be available on the [class website](https://itamarcaspi.github.io/ml4econ/lectures.html). The following references and links may be useful. However, note that they do not cover all the material we plan to cover in the class.

## Surveys

* Athey, S. (2018). [The impact of machine learning on economics](https://www.nber.org/chapters/c14009.pdf). In _The Economics of Artificial Intelligence: An Agenda_. University of Chicago Press.  

* Athey, S., & Imbens, G. W. (2017). [The state of applied econometrics: Causality and policy evaluation](https://www.aeaweb.org/articles?id=10.1257/jep.31.2.3). _Journal of Economic Perspectives_, 31(2), 3-32.  

* Belloni, A., Chernozhukov, V., & Hansen, C. (2014). [High-dimensional methods and inference on structural and treatment effects](https://www.aeaweb.org/articles?id=10.1257/jep.28.2.29). _Journal of Economic Perspectives_, 28(2), 29-50.  

* Mullainathan, S., & Spiess, J. (2017). [Machine learning: an applied econometric approach](https://www.aeaweb.org/articles?id=10.1257/jep.31.2.87). _Journal of Economic Perspectives_, 31(2), 87-106.  

* Varian, H. R. (2014). [Big data: New tricks for econometrics](https://www.aeaweb.org/articles?id=10.1257/jep.28.2.3). _Journal of Economic Perspectives_, 28(2), 3-28.  

## Textbooks

#### __Machine Learning__

[**An Introduction to Statistical Learning with Applications in R**](http://www-bcf.usc.edu/~gareth/ISL) <br>
*Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani* <br>
This book provides a hands-on and R-based introduction to Machine Learning. <br/>
_PDF available online_

[**Elements of Statistical Learning**](http://statweb.stanford.edu/~tibs/ElemStatLearn) <br>
*Trevor Hastie, Robert Tibshirani and Jerome Friedman* <br/>
This book covers the same topics as previous book (and more), however, it provides more rigorous treatment. <br>
_PDF available online_

[**Machine Learning - A Probablistic Prespective**](https://www.cs.ubc.ca/~murphyk/MLbook/)  
*Kevin P. Murphy*  
This book includes basic topics in statistical modeling, as well as advanced machine learning topics.  It comes with Matlab code to reproduce almost every figure and algorithm, discussed in the book.

#### __Sparse Models__

The following two books presents a detailed account of recently developed approaches to estimating models containing a large number of parameters, including the Lasso and versions of it: 

[**Statistical Learning with Sparsity - The Lasso and Generalizations**](https://web.stanford.edu/~hastie/StatLearnSparsity/)  
*Trevor Hastie, Robert Tibshirani, and Martin Wainwright*  
In book contains an introduction to and a summary of the actively developing field of statistical learning with sparse models.  
_PDF available online_

[**Statistics for High-Dimensional Data - Methods, Theory and Applications**](https://www.springer.com/gp/book/9783642201912)   
*Peter Buhlmann, and Sara van de Geer*  
This book brings together methodological concepts, computational algorithms, a
few applications and mathematical theory for high-dimensional statistics.  


#### __Causal Inference__

The following two textbooks provide a graduate level treatment of causal inference in social sciences:

[**Mostly Harmless Econometrics**](http://www.mostlyharmlesseconometrics.com/) <br/>
*Joshua Angrist and Jorn-Steffen Pischke*

[**Causal Inference for Statistics, Social, and Biomedical Sciences**](https://doi.org/10.1017/CBO9781139025751) <br/>
*Guido Imbens and Donald Rubin*

[**The Book of Why: The New Science of Cause and Effect**](https://www.amazon.com/Book-Why-Science-Cause-Effect/dp/046509760X)  
_Judea Pearl and Dana Mackenzie_
Pearl and Mackenzie's book is a must for anyone interested in causality. It lays the foundations of Pearl's approach to causal inference in plain English and graphs with very few equations.


#### __Text Mining__

[**Text Mining with R - A Tidy Approach**](https://www.tidytextmining.com/)  
_Julia Silge and David Robinson_  
The go-to textbook for those interested in textmining with R.


## Webcasts

+ AEA 2018 Continuing Education, [”Machine Learning and Econometrics”](https://www.aeaweb.org/conference/cont-ed/2018-webcasts) (Athey and
Imbens).  
+ NBER 2015 Method Lectures, [”Lectures on Machine Learning”](https://www.nber.org/econometrics_minicourse_2015/) (Athey and Imbens).  
+ NBER 2013 Method Lectures, ["Econometric Methods for High-Dimensional Data""](https://www.nber.org/econometrics_minicourse_2013/) (Victor Chernozhukov, Matthew Gentzkow, Christian Hansen, Jesse Shapiro, Matthew Taddy).  
+ [”Machine Learning and Prediction in Economics and Finance”](https://www.youtube.com/watch?v=xl3yQBhI6vY), Sendhil Mullainathan, AFA
Lecture, 2017.  
+ ["The Impact of Machine Learning on Econometrics and Economics" ](https://www.aeaweb.org/webcasts/2019/aea-afa-joint-luncheon-impact-of-machine-learning), Susan Athey, AEA Lecture, 2019.


## Economists (mostly) to follow

* [Susan Athey](https://www.gsb.stanford.edu/faculty-research/faculty/susan-athey) (Stanford)  
* [Alexandre Belloni](https://faculty.fuqua.duke.edu/~abn5/belloni-index.html) (Duke)  
* [Victor Chernozhukov](http://www.mit.edu/~vchern/) (MIT)  
* [Francis Diebols](https://www.sas.upenn.edu/~fdiebold/)  
* [Christiaמ Hansen](https://voices.uchicago.edu/christianhansen/) (Chicago)
* [Guido Imbens](https://www.gsb.stanford.edu/faculty-research/faculty/guido-w-imbens) (Stanford)  
* [Maximilian Kasy](https://maxkasy.github.io/home/) (Harvard)  
* [Sendhil Mullainathan](https://www.chicagobooth.edu/faculty/directory/m/sendhil-mullainathan)   (Chicago)  
* [Jann Spiess](https://scholar.harvard.edu/spiess) (Harvard)  
* [Stefan Wager](https://web.stanford.edu/~swager/index.html) (Stanford)





