---
title: "R and RStudio"
---

To get started, you first need to install R. Next, we highly recommend using RStudio, an integrated development environment (IDE) that makes working with R much easier (RStudio's setup will be familiar for those of you who have prior experience with Matlab's IDE). RStudio comes with the very handy `RProj` environment and provides many built-in features that help facilitate data analysis and modelling tasks. In addition, RStudio integrates RMarkdown notebooks that and git, thus enabling us to efficiently work with version control. 


### Install R

Go to [CRAN](https://cloud.r-project.org/) and click on the download link that suits your OS.


### Install RStudio

Go to [RStudio](https://www.rstudio.com/) website and click on the download button. The free version is more than what you need for this course.

Three recommended settings:

1. Always use a project-oriented workflow, where each task, assignment, etc. is a standalone project. Remember: If you need your R script to start with`setwd()` and `rm(list=ls())` than are [doing something wrong](https://www.tidyverse.org/articles/2017/12/workflow-vs-script/)!  

2. Go to **Tools -> General Options -> General** and set the Save workspace to .RData on exit to *NEVER*. This option improves the reproducability of your projects since it causes you to start every project in a new R session, i.e., a clean environment without any objects or packages pre-loaded. 

3. Go to **Tools -> General Options -> Git/SVN** and check the "Enable version control interface to RStudio projects" box. Next, make sure that the "Git executable" points to the git binary file (e.g., "C:/Program Files/Git/bin/git.exe").


### Alternativs to R and RStudio

If for some reason you insist on not using RStudio, we can suggest a couple alternative open-source IDEs:

1. [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/#) coupled with the [IRkernel](https://github.com/IRkernel/IRkernel) extension.
2. [Atom](https://atom.io/) coupled with the [ide-r](https://atom.io/packages/ide-r) and [Hydrogen](https://atom.io/packages/hydrogen) extensions.

Note that all IDEs, RStudio included depend on R being installed.

### Resources for learning R

* Datacamp's [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r) and [Working with the RStudio IDE (Part 1)](https://www.datacamp.com/courses/working-with-the-rstudio-ide-part-1) courses.  

* A [step-by-step guide](https://rforeval.com/courses/setup/) to get you started with R and RStudio.

* Hadley Wickham's [R for Data Science](http://r4ds.had.co.nz/) will teach you how to augment R with the [tidyverse](http://www.tidyverse.org).  

* [RStudio cheat sheets](https://www.rstudio.com/resources/cheatsheets/) where you can find, among others, an RStudio IDE and RMarkdown cheat sheets.  

* [Getting used to R RStudio and RMarkdown](https://rbasics.netlify.com/index.html) will show you how to seamlessly communicate your analysis to others using RMarkdown.


